### ISSUE TITLE
Google Play Crash Report: java.lang.NullPointerException

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#211]
java.lang.NullPointerException
at org.dmfs.tasks.ViewTaskFragment$3.onClick(ViewTaskFragment.java:574)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:170)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5603)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)

**Comment by dmfs** [comment]
Fixed for now, new issue #220 opened though.
