### ISSUE TITLE
Google Play Crash Report: java.lang.NullPointerException

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#214]
java.lang.NullPointerException
	at org.dmfs.tasks.model.contraints.AdjustPercentComplete.apply(AdjustPercentComplete.java:48)
	at org.dmfs.tasks.model.contraints.AdjustPercentComplete.apply(AdjustPercentComplete.java:30)
	at org.dmfs.tasks.model.adapters.FieldAdapter.checkConstraints(FieldAdapter.java:173)
	at org.dmfs.tasks.model.adapters.FieldAdapter.validateAndSet(FieldAdapter.java:112)
	at org.dmfs.tasks.widget.ChoicesFieldEditor.onItemSelected(ChoicesFieldEditor.java:96)
	at android.widget.AdapterView.fireOnSelected(AdapterView.java:875)
	at android.widget.AdapterView.access$200(AdapterView.java:46)
	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:841)
	at android.os.Handler.handleCallback(Handler.java:587)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3701)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by dmfs** [comment]
fixed
