### ISSUE TITLE
Google Play Crash Report: java.lang.StringIndexOutOfBoundsException: length=119; index=119

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#215]
java.lang.StringIndexOutOfBoundsException: length=119; index=119
at org.dmfs.tasks.model.adapters.DescriptionStringFieldAdapter.extractDescription(DescriptionStringFieldAdapter.java:114)
at org.dmfs.tasks.model.adapters.DescriptionStringFieldAdapter.get(DescriptionStringFieldAdapter.java:69)
at org.dmfs.tasks.groupings.BaseTaskViewDescriptor.setDescription(BaseTaskViewDescriptor.java:123)
at org.dmfs.tasks.groupings.ByList$1.populateView(ByList.java:142)
at org.dmfs.tasks.utils.ExpandableGroupDescriptorAdapter.bindChildView(ExpandableGroupDescriptorAdapter.java:150)
at android.widget.CursorTreeAdapter.getChildView(CursorTreeAdapter.java:251)
at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:451)
at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
at android.widget.AbsListView.obtainView(AbsListView.java:2207)
at android.widget.ListView.makeAndAddView(ListView.java:1845)
at android.widget.ListView.fillDown(ListView.java:678)
at android.widget.ListView.fillSpecific(ListView.java:1336)
at android.widget.ListView.layoutChildren(ListView.java:1639)
at android.widget.AbsListView.onLayout(AbsListView.java:2037)
at android.view.View.layout(View.java:14118)
at android.view.ViewGroup.layout(ViewGroup.java:4467)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
at android.view.View.layout(View.java:14118)
at android.view.ViewGroup.layout(ViewGroup.java:4467)
at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
at android.view.View.layout(View.java:14118)
at android.view.ViewGroup.layout(ViewGroup.java:4467)
at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1037)
at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:747)
at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1156)
at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:760)
at android.view.View.layout(View.java:14118)
at android.view.ViewGroup.layout(ViewGroup.java:4467)
at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
at android.view.View.layout(View.java:14118)
at android.view.ViewGroup.layout(ViewGroup.java:4467)
at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
at android.view.View.layout(View.java:14118)
at android.view.ViewGroup.layout(ViewGroup.java:4467)
at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
at android.view.View.layout(View.java:14118)
at android.view.ViewGroup.layout(ViewGroup.java:4467)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
at android.view.View.layout(View.java:14118)
at android.view.ViewGroup.layout(ViewGroup.java:4467)
at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
at android.view.View.layout(View.java:14118)
at android.view.ViewGroup.layout(ViewGroup.java:4467)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1947)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4872)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
at android.view.Choreographer.doCallbacks(Choreographer.java:579)
at android.view.Choreographer.doFrame(Choreographer.java:548)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
at android.os.Handler.handleCallback(Handler.java:800)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5371)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)

**Comment by dmfs** [comment]
fixed
