### ISSUE TITLE
Google Play Crash Report: java.lang.NoClassDefFoundError: android.support.v7.view.menu.MenuBuilder

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#216]
This one doesn't appear to involve our code at all. Might be a bug in the ROM

```
java.lang.NoClassDefFoundError: android.support.v7.view.menu.MenuBuilder
at android.support.v7.widget.ActionMenuView.getMenu(ActionMenuView.java:642)
at android.support.v7.widget.Toolbar.ensureMenu(Toolbar.java:868)
at android.support.v7.widget.Toolbar.getMenu(Toolbar.java:839)
at android.support.v7.widget.ToolbarWidgetWrapper.getMenu(ToolbarWidgetWrapper.java:694)
at android.support.v7.app.ToolbarActionBar.getMenu(ToolbarActionBar.java:578)
at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:436)
at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:60)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
at android.view.Choreographer.doCallbacks(Choreographer.java:579)
at android.view.Choreographer.doFrame(Choreographer.java:547)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
at android.os.Handler.handleCallback(Handler.java:800)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5391)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by dmfs** [comment]
Postponed for now. Need more info.
