### ISSUE TITLE
Google Play Crash Report: android.database.sqlite.SQLiteException: index FTS_Content_fts_type_idx already exists

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#217]
android.database.sqlite.SQLiteException: index FTS_Content_fts_type_idx already exists (code 1): , while compiling: CREATE  UNIQUE INDEX FTS_Content_fts_type_idx ON FTS_Content (fts_type, fts_task_id, fts_property_id);
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
	at org.dmfs.provider.tasks.FTSDatabaseHelper.onUpgrade(Unknown Source)
	at org.dmfs.provider.tasks.TaskDatabaseHelper.onUpgrade(Unknown Source)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at org.dmfs.provider.tasks.SQLiteContentProvider.update(Unknown Source)
	at org.dmfs.provider.tasks.TaskProvider.update(Unknown Source)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:355)
	at android.content.ContentResolver.update(ContentResolver.java:1362)
	at org.dmfs.provider.tasks.ContentOperation.fire(Unknown Source)
	at org.dmfs.provider.tasks.TaskProvider$1.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by dmfs** [comment]
fixed in dmfs/opentasks-provider#7
