### ISSUE TITLE
Crash if the home button is pressed too quickly

### ISSUE THREAD

**Issue by daladim** [dmfs/opentasks#340]
Hello,

Thanks for this great app!
I have had a crash for a long time, I've just figured out how to reproduce it \o/
I'm not experienced enough on Android apps (yet?) to be able to fix it, so I rather open an issue

**To reproduce it**
Open the app. Click on a list so that it unwinds, and gives access to the 'quick add' button (the little plus at the right of the screen).
Click this 'quick add' button (not the large, main 'add' floating button at the bottom the screen), and type any name in the Title field.
Click "Save", then press the Android home button (timing is important) when the dialog has changed to "Task created", but before the dialog has disappeared.

**Expected behaviour:**
Task is saved, and Android leads the user back to the launcher screen

**Actual behaviour:**
Task is saved, Android leads the user back to the launcher screen, but OpenTasks crashes, and Android show the "Unfortunately, OpenTasks has stopped" notification.
The log of the crash is
`06-22 20:31:52.892 3640-3640/? E/AndroidRuntime: FATAL EXCEPTION: main
     Process: org.dmfs.tasks, PID: 3640
     java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
         at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1489)
         at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1507)
         at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
         at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
         at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:201)
         at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:167)
         at org.dmfs.tasks.QuickAddDialogFragment$1.run(QuickAddDialogFragment.java:470)
         at android.os.Handler.handleCallback(Handler.java:739)
         at android.os.Handler.dispatchMessage(Handler.java:95)
         at android.os.Looper.loop(Looper.java:148)
         at android.app.ActivityThread.main(ActivityThread.java:5417)
         at java.lang.reflect.Method.invoke(Native Method)
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

I am using a Google Nexus 5, Android 6.0.1, OpenTasks 1.1.8.2, and mainly caldav-synced task lists (synced using the CalDAV-Sync app)

Feel free to ask me anything if you need more details
Thanks

**Comment by dmfs** [comment]
Thx, I think we have fixed this with #192. I'm going to publish a new version next week, so this should be no longer an issue. Please reopen if this still happens after the update.

**Comment by daladim** [comment]
Sorry I didn't find the previous issues about this bug.
I'm too lazy to build the app myself, I'll just wait until next week then. Thank you!
