### ISSUE TITLE
Google Play Crash Report: android.database.sqlite.SQLiteException

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#382]
```
android.database.sqlite.SQLiteException: 
  at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method:0)
  at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1113)
  at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:686)
  at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
  at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
  at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
  at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1769)
  at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1700)
  at org.dmfs.provider.tasks.FTSDatabaseHelper.onUpgrade(FTSDatabaseHelper.java:187)
  at org.dmfs.provider.tasks.TaskDatabaseHelper.onUpgrade(TaskDatabaseHelper.java:783)
  at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:257)
  at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
  at org.dmfs.provider.tasks.SQLiteContentProvider.update(SQLiteContentProvider.java:191)
  at org.dmfs.provider.tasks.TaskProvider.update(TaskProvider.java:104)
  at android.content.ContentProvider$Transport.update(ContentProvider.java:235)
  at android.content.ContentResolver.update(ContentResolver.java:995)
  at org.dmfs.provider.tasks.ContentOperation.fire(ContentOperation.java:342)
  at org.dmfs.provider.tasks.TaskProvider$1.run(TaskProvider.java:1152)
  at android.os.Handler.handleCallback(Handler.java:725)
  at android.os.Handler.dispatchMessage(Handler.java:92)
  at android.os.Looper.loop(Looper.java:175)
  at android.os.HandlerThread.run(HandlerThread.java:60)
```

No further information.

**Comment by dmfs** [comment]
@lemonboston please look into this and let me know if you can solve it.

**Comment by lemonboston** [comment]
I can see from the stacktrace that the exception comes when upgrading the SQLite database and executing the SQL statement here in `FTSDatabaseHelper`:

```java
    public static void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion)
    {
        if (oldVersion < 8)
        {
            initializeFTS(db);
            initializeFTSContent(db);
        }
        if (oldVersion < 16)
        {
            db.execSQL(TaskDatabaseHelper.createIndexString(FTS_CONTENT_TABLE, true, FTSContentColumns.TYPE, FTSContentColumns.TASK_ID,
                    FTSContentColumns.PROPERTY_ID));
        }
    }

-->

public final static String createIndexString(String table, boolean unique, String... fields)
    {
        if (fields == null || fields.length < 1)
        {
            throw new IllegalArgumentException("need at least one field to build an index!");
        }

        StringBuffer buffer = new StringBuffer();

        // Index name is constructed like this: tablename_fields[0]_idx
        buffer.append("CREATE ");
        if (unique)
        {
            buffer.append(" UNIQUE ");
        }
        buffer.append("INDEX ");
        buffer.append(table).append("_").append(fields[0]).append("_idx ON ");
        buffer.append(table).append(" (");
        buffer.append(fields[0]);
        for (int i = 1; i < fields.length; i++)
        {
            buffer.append(", ").append(fields[i]);
        }
        buffer.append(");");

        return buffer.toString();

    }
```

I don't think I can solve this with my current knowledge about these parts (tasks db model, fts solution, db indexes in general) or at least it would be very inefficient if I try to look into this, I think.

**Comment by lemonboston** [comment]
I could reproduce it by installing from master with changed db level 15, adding tasks (2 task list) and then updating the app with level 16.
(Had to also put `android:allowBackup="false"` in the manifest to disable loading db from backup when clean installing)

Stacktrace with the message:
```java
11-28 18:47:43.161 21700-21761/org.dmfs.tasks I/TaskDatabaseHelper: updgrading db from 15 to 16
11-28 18:47:43.161 21700-21761/org.dmfs.tasks E/SQLiteLog: (1) index Instances_instance_start_sorting_idx already exists
11-28 18:47:43.167 21700-21761/org.dmfs.tasks E/AccountManager: Can't update accounts
                                                                android.database.sqlite.SQLiteException: index Instances_instance_start_sorting_idx already exists (code 1): , while compiling: CREATE INDEX Instances_instance_start_sorting_idx ON Instances (instance_start_sorting);
                                                                    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                    at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                    at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                    at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1674)
                                                                    at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
                                                                    at org.dmfs.provider.tasks.TaskDatabaseHelper.onUpgrade(TaskDatabaseHelper.java:783)
                                                                    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
                                                                    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                    at org.dmfs.provider.tasks.TaskProvider.onAccountsUpdated(TaskProvider.java:1287)
                                                                    at android.accounts.AccountManager$19.run(AccountManager.java:1861)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
```
