### ISSUE TITLE
Google Play Crash Report: java.lang.NullPointerException: 

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#383]
```
java.lang.NullPointerException: 
  at android.app.LoadedApk.getAssets(LoadedApk.java:528)
  at android.app.LoadedApk.makeApplication(LoadedApk.java:584)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4526)
  at android.app.ActivityThread.access$1500(ActivityThread.java:151)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5254)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```
Affects various devices with Android 5.0 and 5.1 (no Android 6 or 7 yet).

**Comment by lemonboston** [comment]
Looks like a framework bug during or after app update.

See:
https://github.com/ekux44/LampShade/issues/95
https://issuetracker.google.com/issues/36972466

The bug is not solved by Google yet, there is a dirty workaround suggested in the thread, reportedly used by Square and Groupon:
https://issuetracker.google.com/issues/36972466#comment14
```
public class DevToolsApplication extends Application { 
    private static final String TAG = "DevToolsApplication"; 

    @Override 
    public void onCreate() { 
        super.onCreate(); 
        AppLogger.i(TAG, "app start..."); 
        checkAppReplacingState(); 
    } 

    private void checkAppReplacingState() { 
        if (getResources() == null) { 
            AppLogger.w(TAG, "app is replacing...kill"); 
            Process.killProcess(Process.myPid()); 
        } 
    } 
} 
```

I am going to submit a PR with this.
