### ISSUE TITLE
Google Play Crash Report: java.lang.ClassCastException

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#384]
```
java.lang.ClassCastException: 
  at org.dmfs.tasks.groupings.ByPriority$2$1.onClick(ByPriority.java:268)
  at android.view.View.performClick(View.java:4640)
  at android.view.View$PerformClick.run(View.java:19425)
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:146)
  at android.app.ActivityThread.main(ActivityThread.java:5593)
  at java.lang.reflect.Method.invokeNative(Native Method:0)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
  at dalvik.system.NativeStart.main(Native Method:0)
```

**Comment by dmfs** [comment]
Just noted that this is probably the same as #380

**Comment by dmfs** [comment]
duplicate of #380
