### ISSUE TITLE
Program freezing when open

### ISSUE THREAD

**Issue by ufa** [dmfs/opentasks#455]
Today My OpenTasks program started to freeze. When I open it, it shows me the main screen without any tasks and an unresponsive GUI until force close dialogue appears.
This begin to happen with me (Zenfone 2 with LineageOS) and another cellphone (Galaxy Edge 7) today. 

We are using the F-Droid version, syncing with a Radicale local server + DAVDriod. All calendar + Tasks + Contacts permissions given

Logcat (logcat | grep org.dmfs.tasks):

`10-14 18:07:57.715  1827  2909 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.dmfs.tasks/.TaskListActivity (has extras)} from uid 10031 on display 0
10-14 18:07:57.794  1827  2866 I ActivityManager: Start proc 9942:org.dmfs.tasks/u0a134 for activity org.dmfs.tasks/.TaskListActivity
10-14 18:07:57.828  9942  9942 W System  : ClassLoader referenced unknown path: /mnt/expand/105d61fe-501b-44e2-b702-584cdb928802/app/org.dmfs.tasks-1/lib/x86
10-14 18:07:57.978  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:07:57.981  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: error inflating model for at.bitfire.davdroid
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: org.dmfs.tasks.model.ModelInflaterException: No model definition found for package at.bitfire.davdroid
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: 	at org.dmfs.tasks.model.XmlModel.inflate(XmlModel.java:289)
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: 	at org.dmfs.tasks.model.Sources.getAccounts(Sources.java:180)
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: 	at org.dmfs.tasks.model.Sources.<init>(Sources.java:142)
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: 	at org.dmfs.tasks.model.Sources.getInstance(Sources.java:84)
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: 	at org.dmfs.tasks.utils.AsyncModelLoader.doInBackground(AsyncModelLoader.java:73)
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: 	at org.dmfs.tasks.utils.AsyncModelLoader.doInBackground(AsyncModelLoader.java:36)
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
10-14 18:07:58.010  9942  9962 E org.dmfs.tasks.model.Sources: 	at java.lang.Thread.run(Thread.java:761)
10-14 18:07:58.172  1827  1848 I ActivityManager: Displayed org.dmfs.tasks/.TaskListActivity: +428ms
10-14 18:08:28.097  9976  9992 I davdroid: [syncadapter.SyncAdapterService] org.dmfs.tasks sync of Account {name=ufa@technotroll.org, type=bitfire.at.davdroid} has been initiated
10-14 18:08:28.181  9942  9954 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:28.182  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:28.202  9942  9994 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:28.203  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:29.047  9942  9994 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:29.048  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:29.482  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:29.483  9942  9954 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:29.489  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:29.491  9976  9992 I davdroid: [syncadapter.SyncAdapterService] Sync for org.dmfs.tasks complete
10-14 18:08:32.992  9976 10001 I davdroid: [syncadapter.SyncAdapterService] org.dmfs.tasks sync of Account {name=jasmin@seguindoestrelas.org, type=bitfire.at.davdroid} has been initiated
10-14 18:08:33.049  9942  9955 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:33.050  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:35.600  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:35.600  9942  9955 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:35.603  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:35.708  9942  9995 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:35.710  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:35.993  9942  9954 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:35.994  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:36.160  9942  9994 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:36.162  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:36.304  9942  9955 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:36.307  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:36.452  9942  9995 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:36.454  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:36.614  9942  9954 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:36.616  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:36.792  9942  9994 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:36.795  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:37.280  9942  9955 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:37.282  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:37.434  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:37.434  9942  9995 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:37.574  9942  9954 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:37.576  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:37.883  9942  9994 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:37.886  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:38.053  9942  9955 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:38.055  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:38.239  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:38.240  9942  9995 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:38.247  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:38.378  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:38.381  9942  9954 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:38.385  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:38.404  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:38.405  9942  9994 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:38.410  9976 10001 I davdroid: [syncadapter.SyncAdapterService] Sync for org.dmfs.tasks complete
10-14 18:08:38.414  9942  9959 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:08:58.167  1827  1841 W BroadcastQueue: Receiver during timeout: ResolveInfo{b95113e org.dmfs.tasks/.homescreen.TaskListWidgetProviderLarge m=0x308000}
10-14 18:09:00.274  1827  1841 E ActivityManager: ANR in org.dmfs.tasks
10-14 18:09:00.274  1827  1841 E ActivityManager: Reason: Broadcast of Intent { act=android.intent.action.PROVIDER_CHANGED dat=content://org.dmfs.tasks flg=0x10 cmp=org.dmfs.tasks/.homescreen.TaskListWidgetProviderLarge }
10-14 18:09:00.274  1827  1841 E ActivityManager:  +0% 9942/org.dmfs.tasks: 0% user + 0% kernel
10-14 18:09:00.274  1827  1841 E ActivityManager:   98% 9942/org.dmfs.tasks: 98% user + 0% kernel / faults: 133 minor
10-14 18:09:00.274  1827  1841 E ActivityManager:     100% 9942/org.dmfs.tasks: 100% user + 0% kernel
10-14 18:09:03.868  1827  1842 W ActivityManager:   Force finishing activity org.dmfs.tasks/.TaskListActivity
10-14 18:09:03.876  1827  1842 I ActivityManager: Killing 9942:org.dmfs.tasks/u0a134 (adj 0): user request after error
10-14 18:09:03.937  1827  1922 W InputDispatcher: channel '873ce48 org.dmfs.tasks/org.dmfs.tasks.TaskListActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-14 18:09:03.937  1827  1922 E InputDispatcher: channel '873ce48 org.dmfs.tasks/org.dmfs.tasks.TaskListActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-14 18:09:03.965  1827  1838 I WindowManager: WIN DEATH: Window{873ce48 u0 org.dmfs.tasks/org.dmfs.tasks.TaskListActivity}
10-14 18:09:03.965  1827  1838 W InputDispatcher: Attempted to unregister already unregistered input channel '873ce48 org.dmfs.tasks/org.dmfs.tasks.TaskListActivity (server)'
10-14 18:09:03.986  1827  1841 I ActivityManager: Start proc 10014:org.dmfs.tasks/u0a134 for broadcast org.dmfs.tasks/.homescreen.TaskListWidgetProviderLarge
10-14 18:09:04.014 10014 10014 W System  : ClassLoader referenced unknown path: /mnt/expand/105d61fe-501b-44e2-b702-584cdb928802/app/org.dmfs.tasks-1/lib/x86
10-14 18:09:04.145 10014 10030 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)
10-14 18:09:04.149 10014 10030 W ContentResolver: Failed to get type for: content://org.dmfs.tasks (Unsupported URI: content://org.dmfs.tasks)

`

Any help will be much appreciated

**Comment by ufa** [comment]
Update: same error with google play version.

**Comment by ufa** [comment]
It was a DAVdroid issue. Just updated DAVdroid and everything is running now
