### ISSUE TITLE
Deleting task in list (by swiping) doesn't clear details view.

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#521]
If I select a task in two-pane mode and swipe right to delete it (after it has already been completed) it's still visible in the details view. Clicking edit in the details view will crash the app.

**Comment by lemonboston** [comment]
I could reproduce it with the crash when clicking edit, and the nice thing is that this is the same stacktrace as in https://github.com/dmfs/opentasks/issues/511. So we now have a way to test that.

```
11-30 21:14:33.831 16396-16396/org.dmfs.tasks E/AndroidRuntime: FATAL EXCEPTION: main
        Process: org.dmfs.tasks, PID: 16396
        java.lang.RuntimeException: Unable to start activity ComponentInfo{org.dmfs.tasks/org.dmfs.tasks.EditTaskActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2802)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
            at android.app.ActivityThread.access$900(ActivityThread.java:181)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:6134)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
            at org.dmfs.tasks.model.adapters.ColorFieldAdapter.get(ColorFieldAdapter.java:93)
            at org.dmfs.tasks.EditTaskFragment.onCreateView(EditTaskFragment.java:299)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:2248)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1340)
            at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
            at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
            at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
            at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
            at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
            at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:379)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
            at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
            at android.app.Activity.performStart(Activity.java:6412)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2765)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867) 
            at android.app.ActivityThread.access$900(ActivityThread.java:181) 
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476) 
            at android.os.Handler.dispatchMessage(Handler.java:102) 
            at android.os.Looper.loop(Looper.java:145) 
            at android.app.ActivityThread.main(ActivityThread.java:6134) 
            at java.lang.reflect.Method.invoke(Native Method) 
            at java.lang.reflect.Method.invoke(Method.java:372) 
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 
```
