### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#575]
I've just got this crash after changing the device time zone (I don't think that this is the actual reason though). We also see reports about this on Google Play.
```
java.lang.IllegalStateException: this should only be called when the cursor is valid
	at android.widget.CursorTreeAdapter.getGroupView(CursorTreeAdapter.java:198)
	at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:446)
	at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
	at android.widget.AbsListView.obtainView(AbsListView.java:2363)
	at android.widget.ListView.makeAndAddView(ListView.java:1970)
	at android.widget.ListView.fillDown(ListView.java:704)
	at android.widget.ListView.fillSpecific(ListView.java:1412)
	at android.widget.ListView.layoutChildren(ListView.java:1708)
	at android.widget.AbsListView.onLayout(AbsListView.java:2162)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
	at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1397)
	at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17637)
	at android.view.ViewGroup.layout(ViewGroup.java:5575)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:17637)
       …
```

**Comment by dmfs** [comment]
Duplicated by #758
