### ISSUE TITLE
Crash when quickly adding task with dialog and tapping outside

### ISSUE THREAD

**Issue by lemonboston** [dmfs/opentasks#629]
I just encountered this once now, not sure how often this can happen.

I was adding tasks quickly with the Quick Add dialog using 'Save and continue' button and then tapped outside of the dialog (while the tasks were also presumably being added to the list UI)

- Tablet (Samsung Galaxy Tab 4), Android 5.0.2
- landscape mode
- on branch `mx/624-task-details-fragment-replace` (TODO PR add number here), but it seems unrelated to the changes there

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.support.v4.app.FragmentActivity.getSystemService(java.lang.String)' on a null object reference
    at org.dmfs.tasks.QuickAddDialogFragment$2.run(QuickAddDialogFragment.java:512)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6134)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

The relevant code part:
```java
    private final Runnable mReset = new Runnable()
    {

        @Override
        public void run()
        {
            mContent.animate().alpha(1).setDuration(250).start();
            mConfirmation.animate().alpha(0).setDuration(250).start();
            mSaveButton.setEnabled(true);
            mSaveAndNextButton.setEnabled(true);

            // reset view
            mEditText.selectAll();

            // bring the keyboard up again
            mEditText.requestFocus();
line:512:   InputMethodManager inputMethodManager = (InputMethodManager) getActivity().getSystemService(Context.INPUT_METHOD_SERVICE);
            inputMethodManager.showSoftInput(mEditText, 0);
        }
    };
```

It seems the `DialogFragment` has detached from the `Activity` by the time this reset runnable was run.

**Comment by lemonboston** [comment]
I am closing this since the related pull request has been merged.
