### ISSUE TITLE
plus button on home screen widget is broken

### ISSUE THREAD

**Issue by aol-nnov** [dmfs/opentasks#759]
when I try to press the aforementioned button, nothing happens.

Stacktrace:
```
01-30 08:27:17.043  6566  6566 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver org.dmfs.tasks.homescreen.TaskListWidgetProvider: android.database.sqlite.SQLiteException: near "AND_id": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT _id FROM Instance_Client_View WHERE ( 1=1  AND _deleted=0) AND (sync_enabled=1 AND distance_from_current <=0 AND_id IN (2)) ORDER BY instance_due_sorting
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3523)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:207)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1759)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: near "AND_id": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT _id FROM Instance_Client_View WHERE ( 1=1  AND _deleted=0) AND (sync_enabled=1 AND distance_from_current <=0 AND_id IN (2)) ORDER BY instance_due_sorting
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1457)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:419)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:296)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at org.dmfs.provider.tasks.TaskProvider.query(TaskProvider.java:705)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.content.ContentProvider.query(ContentProvider.java:1138)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.content.ContentProvider.query(ContentProvider.java:1230)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:251)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:847)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:762)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:720)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at org.dmfs.tasks.homescreen.TaskListWidgetProvider.onReceive(TaskListWidgetProvider.java:87)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3507)
01-30 08:27:17.043  6566  6566 E AndroidRuntime: 	... 8 more
01-30 08:33:36.433  6994  6994 E AndroidRuntime: FATAL EXCEPTION: main
01-30 08:33:36.433  6994  6994 E AndroidRuntime: Process: org.dmfs.tasks, PID: 6994
01-30 08:33:36.433  6994  6994 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver org.dmfs.tasks.homescreen.TaskListWidgetProvider: android.database.sqlite.SQLiteException: near "AND_id": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT _id FROM Instance_Client_View WHERE ( 1=1  AND _deleted=0) AND (sync_enabled=1 AND distance_from_current <=0 AND_id IN (2)) ORDER BY instance_due_sorting
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3523)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.app.ActivityThread.access$1400(ActivityThread.java:207)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1759)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6863)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: near "AND_id": syntax error (code 1 SQLITE_ERROR): , while compiling: SELECT _id FROM Instance_Client_View WHERE ( 1=1  AND _deleted=0) AND (sync_enabled=1 AND distance_from_current <=0 AND_id IN (2)) ORDER BY instance_due_sorting
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:903)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:514)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1457)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:419)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:296)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at org.dmfs.provider.tasks.TaskProvider.query(TaskProvider.java:705)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.content.ContentProvider.query(ContentProvider.java:1138)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.content.ContentProvider.query(ContentProvider.java:1230)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:251)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:847)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:762)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:720)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at org.dmfs.tasks.homescreen.TaskListWidgetProvider.onReceive(TaskListWidgetProvider.java:87)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3507)
01-30 08:33:36.433  6994  6994 E AndroidRuntime: 	... 8 more
```

Adding tasks within an app works though.

Android P, Opentasks 1.1.16-3-ga2567c4b (beta channel)

**Comment by dmfs** [comment]
Looks like I lost a space character in that branch. Should be easy to fix.

**Comment by aol-nnov** [comment]
@dmfs, it seems to me, that it's already fixed in master: https://github.com/dmfs/opentasks/blob/871dbda94cf5bd31bf617cf02a14a22bd18cec0c/opentasks/src/main/java/org/dmfs/tasks/homescreen/TaskListWidgetProvider.java#L87

Would you mind releasing another beta?

**Comment by dmfs** [comment]
The new release is planned for tomorrow.

**Comment by aol-nnov** [comment]
still able to reproduce it in 1.1.17-5-g9cb418e7...

**Comment by dmfs** [comment]
That's weird. I'll check that again. The branch definitely contains a space now between ` AND` and `_id`: https://github.com/dmfs/opentasks/blob/stories/462-basic-recurrence-support/opentasks/src/main/java/org/dmfs/tasks/homescreen/TaskListWidgetProvider.java#L90

**Comment by aol-nnov** [comment]
now it has different logs:
```
02-06 11:17:20.421  1441  1494 W BroadcastQueue: Unable to launch app org.dmfs.tasks/10118 for broadcast Intent { act=CreateTask flg=0x10000010 cmp=org.dmfs.tasks/.homescreen.TaskListWidgetProvider bnds=[942,464][1027,549] (has extras) }: process is bad
```

**Comment by dmfs** [comment]
I've just tested it again and it works for me. Is there any stack trace in the log which gives more information on why the intent can't be launched?

**Comment by aol-nnov** [comment]
@dmfs no stacktraces this time.. only a line that I've quoted earlier today

**Comment by dmfs** [comment]
Oh, wait. I found the issue. I'll push an update later this evening.

**Comment by dmfs** [comment]
Pushed a new version `1.1.17-5-g9b760254` which should fix this. I reverted the changes on `TaskListWidgetProvider.java` in the recurrence branch since they were complete nonsense.

**Comment by aol-nnov** [comment]
Yes, the issue us now fixed. Thank you!
