### ISSUE TITLE
Crash after deleting a task with a notification

### ISSUE THREAD

**Issue by dmfs** [dmfs/opentasks#802]
```
06-07 21:51:10.378 28777 29205 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: Caused by: java.lang.NullPointerException: uri
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:128)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:737)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:704)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:662)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at org.dmfs.tasks.utils.AsyncContentLoader.doInBackground(AsyncContentLoader.java:76)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at org.dmfs.tasks.utils.AsyncContentLoader.doInBackground(AsyncContentLoader.java:34)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-07 21:51:10.378 28777 29205 E AndroidRuntime: 	... 4 more
```

Steps taken:
* Create a task with a due date
* wait for the due notification to show up
* delete the task

**Comment by stackcoder** [comment]
Yes, I have notification disabled on my device. Due date can be changed correctly using an another app.
